// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM0H5PAnpLGyDAYWR-jatZTX5kV9FQ-iE',
    appId: '1:695694961171:web:e18e03d96c5ebb477dade6',
    messagingSenderId: '695694961171',
    projectId: 'utm-bustracker',
    authDomain: 'utm-bustracker.firebaseapp.com',
    databaseURL: 'https://utm-bustracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'utm-bustracker.firebasestorage.app',
    measurementId: 'G-10PHXKZ3B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoxxdCqhsIDwpW6SLKUx9bUXZofP0gcbg',
    appId: '1:695694961171:android:6eccd7b20df184d77dade6',
    messagingSenderId: '695694961171',
    projectId: 'utm-bustracker',
    databaseURL: 'https://utm-bustracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'utm-bustracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAODZ53w8sk7WduFDS0JwaQU1lt01zctVU',
    appId: '1:695694961171:ios:b796cb9dec6a05f17dade6',
    messagingSenderId: '695694961171',
    projectId: 'utm-bustracker',
    databaseURL: 'https://utm-bustracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'utm-bustracker.firebasestorage.app',
    iosBundleId: 'com.utmbustrack.utmBusTracker',
  );
}
